### ISSUE TITLE
provider register not work as expected

### ISSUE THREAD

**Issue by weiwee** [FederatedAI/FATE-Flow#163]
1. Try to

register a SQL-related components with 

```json
{
  "name": "fate_sql",
  "version": "0.1",
  "path": "python/fate_sql"
}
```

2. Exception

db related exception occur with keyError

As `register user-provided provider` is a planed feature in `1.7.0`, we hope this issue could be fixed as soon as possible 🙏

**Comment by jat001** [comment]
could you plz provide the full exception traceback?

**Comment by weiwee** [comment]
```root /workspaces/fate-sql (master) 
$ /venv/sql/bin/flow provider register -c /workspaces/fate-sql/register_provider.json
{
    "retcode": 100,
    "retmsg": "'fate_sql'"
}
root /workspaces/fate-sql (master) 
$ cat /workspaces/fate-sql/register_provider.json
{
  "name": "fate_sql",
  "version": "0.1",
  "path": "python/fate_sql_components/fate_sql"
}
root /workspaces/fate-sql (master) $ 
```

exception:
```
ERROR] [2021-12-30 08:57:45,998] [Server] [1065:140653895853824] - [api_utils.server_error_response] [line:49]: 'fate_sql'
Traceback (most recent call last):
  File "/venv/py36/lib/python3.6/site-packages/flask/app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "/venv/py36/lib/python3.6/site-packages/flask/app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/venv/py36/lib/python3.6/site-packages/flask/app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/venv/py36/lib/python3.6/site-packages/flask/_compat.py", line 35, in reraise
    raise value
  File "/venv/py36/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/venv/py36/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/fate/fateflow/python/fate_flow/utils/detect_utils.py", line 75, in decorated_function
    return func(*_args, **_kwargs)
  File "/fate/fateflow/python/fate_flow/apps/provider_app.py", line 39, in register
    ComponentRegistry.load()
  File "/fate/fateflow/python/fate_flow/db/component_registry.py", line 34, in load
    component_registry = cls.get_from_db(file_utils.load_json_conf_real_time(FATE_FLOW_DEFAULT_COMPONENT_REGISTRY_PATH))
  File "/venv/py36/lib/python3.6/site-packages/peewee.py", line 394, in inner
    return fn(*args, **kwargs)
  File "/fate/fateflow/python/fate_flow/db/component_registry.py", line 151, in get_from_db
    "default": {"version": get_versions()[component_registry["default_settings"][provider_info.f_provider_name]["default_version_key"]]}
KeyError: 'fate_sql'
```
