### ISSUE TITLE
heterolr执行报错，提示processor in session meta is not valid，求助定位思路

### ISSUE THREAD

**Issue by MiKKiYang** [FederatedAI/FATE-Flow#207]
对应arbiter节点上heterolr算法组件报错日志
[ERROR] [2022-03-29 12:24:59,438] [202203291210246798510] [30:140092026906368] - [job_tracker.clean_task] [line:491]: cleanup error
Traceback (most recent call last):
  File "/data/projects/fate/fateflow/python/fate_flow/operation/job_tracker.py", line 455, in clean_task
    sess.init_computing(computing_session_id=f"{computing_temp_namespace}_clean", options=session_options)
  File "/data/projects/fate/fate/python/fate_arch/session/_session.py", line 116, in init_computing
    session_id=computing_session_id, options=options
  File "/data/projects/fate/fate/python/fate_arch/computing/eggroll/_csession.py", line 36, in __init__
    self._rp_session = session_init(session_id=session_id, options=options)
  File "/data/projects/fate/eggroll/python/eggroll/core/session.py", line 42, in session_init
    er_session = ErSession(session_id=session_id, options=options)
  File "/data/projects/fate/eggroll/python/eggroll/core/session.py", line 199, in __init__
    self.__session_meta = self._cluster_manager_client.get_or_create_session(session_meta)
  File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 189, in get_or_create_session
    serdes_type=self.__serdes_type))
  File "/data/projects/fate/eggroll/python/eggroll/core/client.py", line 243, in __check_processors
    raise ValueError(f"processor in session meta is not valid: {session_meta}")
ValueError: processor in session meta is not valid: <ErSessionMeta(id=202203291210246798510_hetero_lr_0_0_arbiter_10002_clean, name=, status=NEW, tag=, process
ors=[***, len=1], options=[{'eggroll.session.processors.per.node': '1', 'eggroll.session.deploy.mode': 'cluster'}]) at 0x7f6ab8e38f28>
[ERROR] [2022-03-29 12:25:42,204] [202203291210246798510] [283:139704828536640] - [_session.get_session_from_record] [line:394]: processor in session meta is not valid: <ErSessionMeta(id=202203291210246798510_hetero_lr_0_0_arbiter_10002, name=, status=NEW, tag=, processors=[***, len=1], options=[{'python.venv': '/opt/app-root', 'eggroll.session.deploy.mode': 'cluster', 'python.path': '/data/projects/fate/fate/python/federatedml:/opt/rh/rh-nodejs10/root/usr/lib/python2.7/site-packages:$PYTHONPATH:/data/projects/fate/fate/python:/data/projects/fate/eggroll/python:/data/projects/fate/fateflow/python:/data/projects/fate/fate/python/fate_client', 'eggroll.session.processors.per.node': '1'}]) at 0x7f0f6a7a5908>
[ERROR] [2022-03-29 12:26:14,137] [202203291210246798510] [304:139838163154752] - [_session.get_session_from_record] [line:394]: processor in session meta is not valid: <ErSessionMeta(id=202203291210246798510_hetero_lr_0_0_arbiter_10002, name=, status=NEW, tag=, processors=[***, len=1], options=[{'eggroll.session.deploy.mode': 'cluster', 'python.venv': '/opt/app-root', 'python.path': '/data/projects/fate/fate/python/federatedml:/opt/rh/rh-nodejs10/root/usr/lib/python2.7/site-packages:$PYTHONPATH:/data/projects/fate/fate/python:/data/projects/fate/eggroll/python:/data/projects/fate/fateflow/python:/data/projects/fate/fate/python/fate_client', 'eggroll.session.processors.per.node': '1'}]) at 0x7f2e75d72908>

对应arbiter节点上session_processor表中的数据：
![image](https://user-images.githubusercontent.com/38832234/160612293-9f9bf605-840f-4a86-b147-738d227777a7.png)

**Comment by MiKKiYang** [comment]
@jat001 @dylan-fan @jarviszeng-zjc 各位老师给点指导意见吧、、、tks so much!!!

**Comment by MiKKiYang** [comment]
this problem has fixed by myself，if u use kubefate to create fate on k8s，and u need to connect external mysql，you should manually create the required tables and data，and the point is!!!  IN THIS SQL ''' INSERT INTO server_node (host, port, node_type, status) values ('nodemanager-0', '9461', 'NODE_MANAGER', 'HEALTHY'); ''', host field‘s VALUE must be nodemanager-number, even if just one nodemanager

![Uploading image.png…]()
