### ISSUE TITLE
集群迁移无法执行预测任务

### ISSUE THREAD

**Issue by zhanhtCN** [FederatedAI/FATE-Flow#230]
**System information**

centos 7,  fate1.7

**Describe the current behavior**
参考文档：https://federatedai.github.io/FATE-Flow/latest/zh/fate_flow_model_migration/#_2
完成模型迁移后，在新集群，执行预测任务，报错
原机器migrate结果截图
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/96578077/164427129-169df269-98da-4d86-a9eb-f4362e84d64e.png">
目标机器import截图
<img width="1149" alt="image" src="https://user-images.githubusercontent.com/96578077/164427278-2d72cad1-e344-4085-8ab0-340e6c1fc526.png">

**Describe the expected behavior**

**Other info / logs** Include any logs or source code that would be helpful to
配置信息：
migrate json
`{
  "job_parameters": {
    "federated_mode": "MULTIPLE"
  },
  "role": {
    "guest": [
      10005
    ],
    "host": [
      10003
    ]
  },
  "execute_party": {
    "guest": [
      10005
    ],
    "host": [
      10003
    ]
  },
  "migrate_initiator": {
    "role": "guest",
    "party_id": 10005
  },
  "migrate_role": {
    "guest": [
      10001
    ],
    "host": [
      10002
    ]
  },
  "model_id": "guest-10005#host-10003#model",
  "model_version": "202204161500311591470"
}`

import 配置
`{
  "role": "guest",
  "party_id": 10001,
  "model_id": "guest-10001#host-10002#model",
  "model_version": "202204210856597457810",
  "file": "/data/projects/fate/examples/zhanht/migrate/guest#10001#guest-10001#host-10002#model_202204210856597457810.zip"
}`

log日志
[ERROR] [2022-04-21 09:22:10,777] [202204210916388364990] [37172:140459868743488] - [model_loader._run] [line:133]: Get 'model_alias' failed. Trying to find a checkpoint...
Traceback (most recent call last):
  File "./fate/fateflow/python/fate_flow/components/model_loader.py", line 130, in _run
    self.get_model_alias()
  File "./fate/fateflow/python/fate_flow/components/model_loader.py", line 56, in get_model_alias
    raise ValueError('The job was not found.')
ValueError: The job was not found.
[ERROR] [2022-04-21 09:22:10,778] [202204210916388364990] [37172:140459868743488] - [model_loader._run] [line:144]: Read checkpoint error.
Traceback (most recent call last):
  File "./fate/fateflow/python/fate_flow/components/model_loader.py", line 142, in _run
    return self.read_checkpoint()
  File "./fate/fateflow/python/fate_flow/components/model_loader.py", line 101, in read_checkpoint
    raise ValueError('The checkpoint was not found.')
ValueError: The checkpoint was not found.
[ERROR] [2022-04-21 09:22:10,779] [202204210916388364990] [37172:140459868743488] - [task_executor._run_] [line:243]: No checkpoint was found.
Traceback (most recent call last):
  File "./fate/fateflow/python/fate_flow/components/model_loader.py", line 142, in _run
    return self.read_checkpoint()
  File "./fate/fateflow/python/fate_flow/components/model_loader.py", line 101, in read_checkpoint
    raise ValueError('The checkpoint was not found.')
ValueError: The checkpoint was not found.

During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "./fate/fateflow/python/fate_flow/worker/task_executor.py", line 195, in _run_
    cpn_output = run_object.run(cpn_input)
  File "./fate/fateflow/python/fate_flow/components/_base.py", line 149, in run
    method(cpn_input)
  File "./fate/fateflow/python/fate_flow/components/model_loader.py", line 147, in _run
    else 'No checkpoint was found.')
OSError: No checkpoint was found.

**Comment by zhanhtCN** [comment]
一步步按照迁移文档执行，唯一差异：
转移模型文件阶段，因为目标机器也有自己的任务，model_local_cache 不是完整cp到目标机器，
而是复制了任务对应的目录：model_local_cache/guest#10005#guest-10005#host-10003#model/202204161500311591470 目录

**Comment by zhanhtCN** [comment]
然后有个奇怪的，我看模型对应的ckp文件夹下，都是没容器的，不知道是否正常
<img width="872" alt="image" src="https://user-images.githubusercontent.com/96578077/164429046-27320d78-6d3f-45d8-811f-ec46d6c7b5ae.png">

**Comment by zhanhtCN** [comment]
同样的这个，我export模型得到zip，然后把当前机器fate停止，删除fate下所有文件，重新部署fate。
机器再次import 这个zip，是能进行后续的预测任务的

**Comment by zhanhtCN** [comment]
预测任务通过model loader，对应配置
            "model_loader_0": {
                "model_id": "guest-10001#host-10002#model",
                "model_version": "202204210856597457810",
                "component_name": "hetero_secure_boost_0"
            }

**Comment by zhanhtCN** [comment]
> 然后有个奇怪的，我看模型对应的ckp文件夹下，都是没容器的，不知道是否正常 <img alt="image" width="872" src="https://user-images.githubusercontent.com/96578077/164429046-27320d78-6d3f-45d8-811f-ec46d6c7b5ae.png">

我正常使用公共数据集，breast训练个模型，然后用modelloader去预测，预测任务正常，但是全程，看训练那个model下的checkpoint 下文件内容都是空的，所以这个貌似没啥影响

**Comment by zhanhtCN** [comment]
看了下model loader的代码，貌似是先从当前系统中看能否找到这个job，如果找不到job，就去ckp找。
但是模型训练，貌似需要通过callbacks显示的开启ckp。
那么，如果没ckp的已有模型，无法完成跨集群的迁移？
是否能对已经完成训练的模型，生成一份当前最细你的ckp？

**Comment by zhanhtCN** [comment]
@jat001 求大佬帮忙看看

**Comment by jat001** [comment]
迁移后用 model loader 时要指定 `model_alias`，这个值是从 job 里获取的，迁移模型不会复制 job

**Comment by jat001** [comment]
1.9会改成从模型文件里直接获取`model_alias`，现阶段请手工指定`model_alias`

**Comment by jat001** [comment]
> > 迁移后用 model loader 时要指定 `model_alias`，这个值是从 job 里获取的，迁移模型不会复制 job
> 
> 请问，之前job怎么找到这个alias信息，去mysql 吗？

可以从dsl里找
https://github.com/FederatedAI/FATE-Flow/wiki/%E6%9C%AF%E8%AF%AD%E8%A1%A8

**Comment by zhanhtCN** [comment]
> > > 迁移后用 model loader 时要指定 `model_alias`，这个值是从 job 里获取的，迁移模型不会复制 job
> > 
> > 
> > 请问，之前job怎么找到这个alias信息，去mysql 吗？
> 
> 可以从dsl里找 https://github.com/FederatedAI/FATE-Flow/wiki/%E6%9C%AF%E8%AF%AD%E8%A1%A8

ok ,感谢大佬，所以即使之前的模型没有ckp，迁移后，正常带上alias，也是可以正常使用model_loader加载并使用的，是吗？

**Comment by jat001** [comment]
> > > > 迁移后用 model loader 时要指定 `model_alias`，这个值是从 job 里获取的，迁移模型不会复制 job
> > > 
> > > 
> > > 请问，之前job怎么找到这个alias信息，去mysql 吗？
> > 
> > 
> > 可以从dsl里找 https://github.com/FederatedAI/FATE-Flow/wiki/%E6%9C%AF%E8%AF%AD%E8%A1%A8
> 
> ok ,感谢大佬，所以即使之前的模型没有ckp，迁移后，正常带上alias，也是可以正常使用model_loader加载并使用的，是吗？

跟 checkpoint 没有关系，默认找不到模型就会去找 checkpoint，所以会有找不到 checkpoint 的报错，找得到的情况下不会管 checkpoint，除非指定了 `step_index`

**Comment by zhanhtCN** [comment]
> > > > > 迁移后用 model loader 时要指定 `model_alias`，这个值是从 job 里获取的，迁移模型不会复制 job
> > > > 
> > > > 
> > > > 请问，之前job怎么找到这个alias信息，去mysql 吗？
> > > 
> > > 
> > > 可以从dsl里找 https://github.com/FederatedAI/FATE-Flow/wiki/%E6%9C%AF%E8%AF%AD%E8%A1%A8
> > 
> > 
> > ok ,感谢大佬，所以即使之前的模型没有ckp，迁移后，正常带上alias，也是可以正常使用model_loader加载并使用的，是吗？
> 
> 跟 checkpoint 没有关系，默认找不到模型就会去找 checkpoint，所以会有找不到 checkpoint 的报错，找得到的情况下不会管 checkpoint，除非指定了 `step_index`

ok，感谢，那我试试加上alias，看下迁移后是否能正常预测

**Comment by zhanhtCN** [comment]
> > > > > > 迁移后用 model loader 时要指定 `model_alias`，这个值是从 job 里获取的，迁移模型不会复制 job
> > > > > 
> > > > > 
> > > > > 请问，之前job怎么找到这个alias信息，去mysql 吗？
> > > > 
> > > > 
> > > > 可以从dsl里找 https://github.com/FederatedAI/FATE-Flow/wiki/%E6%9C%AF%E8%AF%AD%E8%A1%A8
> > > 
> > > 
> > > ok ,感谢大佬，所以即使之前的模型没有ckp，迁移后，正常带上alias，也是可以正常使用model_loader加载并使用的，是吗？
> > 
> > 
> > 跟 checkpoint 没有关系，默认找不到模型就会去找 checkpoint，所以会有找不到 checkpoint 的报错，找得到的情况下不会管 checkpoint，除非指定了 `step_index`
> 
> ok，感谢，那我试试加上alias，看下迁移后是否能正常预测

问题解决，加上alias后，迁移后的模型能够正常完成预测
